### ISSUE TITLE
Search-Filter-Page

### ISSUE THREAD

**Issue by alicespringfeld** [alicespringfeld/campbay-app#13]
# Value proposition

When tabbing on the filter Icon, the user gets to the Filter Page, where you can choose search categories.

# Description

![image](https://user-images.githubusercontent.com/91462529/143282936-a7e09026-95d8-4099-a17e-eadb8db79f95.png)

# Acceptance criteria

- [x] There should be one filter card with filter tabs for landscape and one with filter tabs for infrastructure
- [x] The user should be able to select his filter options through tabbing on the selected tabs
- [x] Tabbing on the filter-button should send a new search request
- [x] Tabbing on the x-Link should link to the Map Overview Page

# Tasks

- [x] Creating filter page
- [x] Creating landscape filter card Component
- [x] Creating infrastructure filter card Component
- [x] Add select function
- [x] Add filtered search function
- [x] Add x-Link (router)
- [x] Show filtered options on MapOverviewPage (router)
