### ISSUE TITLE
Show ResultMap

### ISSUE THREAD

**Issue by alicespringfeld** [alicespringfeld/campbay-app#14]
# Value proposition
The user should see the results of his search request as spots on the map. When tabbing on one result, it should show a preview pop-up showing a photo from the location.

# Description
![image](https://user-images.githubusercontent.com/91462529/143286517-9f5d0c0f-66a9-4d72-91e4-219cb8800f71.png)

# Acceptance criteria
- [ ]...

# Tasks

- [x] creating showResult function
- [x] creating pop-up-preview Component
- [x] creating tab-event for pop-up preview
