### ISSUE TITLE
Start-Page

### ISSUE THREAD

**Issue by alicespringfeld** [alicespringfeld/campbay-app#5]
# Value proposition
This page is an entry for every user of the app. 

# Description
![image](https://user-images.githubusercontent.com/91462529/143146958-a4594c0a-fa2f-4b36-bdfa-d2d4fcdbbfb0.png)

# Acceptance criteria
- [ ] There should be a background Image
- [ ] Logo and button should be centered
- [ ] Button should link to next page

# Tasks
- [ ] create new startpage branch
- [ ] Logo component
- [ ] Button component
- [ ] Background Image
