### ISSUE TITLE
Build Components in Storybook

### ISSUE THREAD

**Issue by alicespringfeld** [alicespringfeld/campbay-app#6]
# Description
![image](https://user-images.githubusercontent.com/91462529/143149476-f7ad5413-35d5-4a7e-9f9b-7fb504f5c87c.png)
![image](https://user-images.githubusercontent.com/91462529/143150375-6eba7320-2d72-4604-84f9-e8e751da26e7.png)

# Tasks
- [ ] Create SearchBar Component
- [ ] Create UploadPhotos_Card Component
- [ ] Create PopUpPreview_Card Component
- [ ] Create LocationDetail_Card Component
- [ ] Create Landscape_Card Component
- [ ] Create Infrastructure_Card Component
- [ ] Create FooterBar Component
- [ ] Create StartButton Component
- [ ] Create GoBackButton Component
- [ ] Create AddLocationButton Component
- [ ] Create LocationButton Component
- [ ] Create FilterButton Component
