### ISSUE TITLE
Map Overview Page

### ISSUE THREAD

**Issue by alicespringfeld** [alicespringfeld/campbay-app#7]
# Value proposition
At the first page after startpage the user can search spots in his location on a map.

# Description
![image](https://user-images.githubusercontent.com/91462529/143151106-aacb09a9-740a-440a-8ebf-ffb8adccc807.png)

# Acceptance criteria
- [x] There should be shown spots as search-results on the map 
- [x] The user should see his position when tabbing on the location button and automatically search for spots in his location-radius

# Tasks
- [x] integrate leaflet
- [x] Add searchBar Component 
- [x] add search function to search bar
- [x] Add filter Icon
- [x] Add location Icon
- [x] Add location function
- [x] Add FooterBar Component
